#!/bin/bash
#Script nautilus de renommage de séries

OLDIFS="$IFS"
IFS="
"

ext() {
    if [[ -n "$2" ]] && [[ -z "$3" ]]; then
        local zoneCut=`echo $2 | sed -e "s#\.#\n#g" | wc -l`
        local extension=`echo $2 | cut -d '.' -f $zoneCut`

        if [[ "$extension" == "bak" ]] || [[ "$extension" == "old" ]] || [[ -z `echo $extension | sed -e "s#[0-9]##g"` ]]; then
            zoneCut=$((zoneCut - 1))
            extension=`echo $2 | cut -d '.' -f $zoneCut-`
        elif [[ "$extension" == "gz" ]] || [[ $extension == bz* ]] || [[ $extension == "rar" ]]; then
            zoneCut=$((zoneCut - 1))
            local extensionBis=`echo $2 | cut -d '.' -f $zoneCut`

            if [[ "$extensionBis" == "tar" ]] || [[ "$extensionBis" == part* ]];then
                extension=`echo $2 | cut -d '.' -f $zoneCut-`
            fi
        elif [[ "$extension" == "xtm" ]]; then
            zoneCut=$((zoneCut - 2))
            extension=`echo $2 | cut -d '.' -f $zoneCut-`
        fi

        if [[ "$1" == "-e" ]]; then
            echo $extension
        elif [[ "$1" == "-p" ]]; then
            echo ".$extension"
        else
            echo -e "Erreur : vous devez entrez '-e' ou '-p' comme premier paramètre.\next [paramètre] fichier\n'-e' pour l'extension et '-p' pour l'extension précédée d'un point"
        fi
    elif [[ -n "$3" ]]; then
        echo "Erreur : trop d'arguments ! Veuillez n'entrer que deux arguments !"
    else
        echo -e "Erreur : vous devez entrer deux arguments !\next [paramètre] fichier\n'-e' pour l'extension et '-p' pour l'extension précédée d'un point"
    fi
}

nomSerie=`zenity --entry --title="Série :" --text="Nom de la série :"`
if [[ "$?" -ne 0 ]]; then
    exit 1;
fi

ok="n"
while [[ "$ok" == "n" ]]; do
    saison=`zenity --entry --title="Saison :" --text="Numéro de la saison :"`
    if [[ "$?" -ne 0 ]]; then
        exit 1;
    fi

    if [[ -z `echo $saison | sed -e "s#[0-9]##g"` ]]; then
        ok="o"
    else
        zenity --error --title="Saison :" --text="Veuillez entrer un chiffre !"
    fi
done

ok="n"
while [[ "$ok" == "n" ]]; do
    ep=`zenity --entry --title="Épisode :" --text="Numéro du premier épisode à renommer :"`
    if [[ "$?" -ne 0 ]]; then
        exit 1;
    fi

    if [[ -z `echo $ep | sed -e "s#[0-9]##g"` ]]; then
        ok="o"
    else
        zenity --error --title="Épisode :" --text="Veuillez entrer un chiffre !"
    fi
done

i="0"
for i in `seq $ep $(($(echo -e "$NEMO_SCRIPT_SELECTED_FILE_PATHS" | wc -l) - 2 + ep))`; do
    if [[ "$i" -eq "$ep" ]]; then
        titresEpisodes=`zenity --entry --title="Titre des épisodes :" --text="Veuillez entrer le titre de l'épisode $i"`
        if [[ "$?" -ne 0 ]]; then
            exit 1;
        fi
    else
        titresEpisodes=`echo -e "${titresEpisodes}%$(zenity --entry --title="Titre des épisodes :" --text="Veuillez entrer le titre de l'épisode $i")"`
        if [[ "$?" -ne 0 ]]; then
            exit 1;
        fi
    fi
done

i="0"
for fichier in $NEMO_SCRIPT_SELECTED_FILE_PATHS; do
    i=$((i + 1))
    extension=`ext -e "$fichier"`
    titre=`echo "$titresEpisodes" | cut -d '%' -f $i`
    
    if [[ "$saison" -gt 9 ]]; then
        if [[ "$ep" -gt 9 ]]; then
            mv "$fichier" "S${saison}E${ep} - ${nomSerie} - ${titre}.${extension}"
        else
            mv "$fichier" "S${saison}E0${ep} - ${nomSerie} - ${titre}.${extension}"
        fi
    else
        if [[ "$ep" -gt 9 ]]; then
            mv "$fichier" "S0${saison}E${ep} - ${nomSerie} - ${titre}.${extension}"
        else
            mv "$fichier" "S0${saison}E0${ep} - ${nomSerie} - ${titre}.${extension}"
        fi
    fi

    ep=$((ep + 1))
done

IFS="$OLDIFS"

exit 0;
