#!/bin/bash
# bspwm_colors - By BrainlessFrog

# Sourcing colors:
# Variable return the code without '#', use '#${Var}' or '#FF${Var}'
. panel_config

normalColor="#${COLOR_BACKGROUND_BRIGHT}"
preselColor="#${COLOR_TERM_WHITE_BRIGHT}"
defaultColor="#${COLOR_TERM_YELLOW_DARK}"
lockedColor="#${COLOR_TERM_BLUE_DARK}"
stickyColor="#${COLOR_TERM_MAGENTA_DARK}"
privateColor="#${COLOR_TERM_CYAN_DARK}"
urgentColor="#${COLOR_TERM_RED_DARK}"

bspc config focused_border_color "$defaultColor"
bspc config active_border_color "$defaultColor"
bspc config normal_border_color "$normalColor"

bspc config presel_border_color "$preselColor"

bspc config focused_locked_border_color "$lockedColor"
bspc config active_locked_border_color "$lockedColor"
bspc config normal_locked_border_color "$normalColor"

bspc config focused_sticky_border_color "$stickyColor"
bspc config active_sticky_border_color "$stickyColor"
bspc config normal_sticky_border_color "$normalColor"

bspc config focused_private_border_color "$privateColor"
bspc config active_private_border_color "$privateColor"
bspc config normal_private_border_color "$normalColor"

bspc config urgent_border_color "$urgentColor"
