#!/bin/bash

windowID="$1"
windowClass="$2"
windowInstance="$3"
#logFile="$(dirname \"$0\")/er_log.txt"
logFile="/tmp/er_log.txt"

getDebug() {
    local winID="$1"
    local winClass="$2"
    local winInstance="$3"
    local winName=`xprop -id "$winID" | grep "WM_NAME" | head -n 1 | cut -d '"' -f 2`
    local winRole=`xprop -id "$winID" | grep "WM_WINDOW_ROLE" | cut -d '"' -f 2`
    local debugFile="$4"

    echo "ID:          $winID" >> $debugFile
    echo "Class:       $winClass" >> $debugFile
    echo "Instance:    $winInstance" >> $debugFile
    echo "Name:        $winName" >> $debugFile
    echo "Role:        $winRole" >> $debugFile
    echo "" >> $debugFile
}

getWindowName() {
    local winID="$1"
    local winName=`xprop -id "$winID" | grep "WM_NAME" | head -n 1 | cut -d '"' -f 2`

    echo "$winName"
}

getWindowRole() {
    local winID="$1"
    local winRole=`xprop -id "$winID" | grep "WM_WINDOW_ROLE" | cut -d '"' -f 2`

    echo "$winRole"
}

# Let the application some time to launch
sleep 1;

# Debugging
#getDebug $windowID $windowClass $windowInstance $logFile

# Rules
case "$windowClass" in
    "Firefox")
        windowName=`getWindowName "$windowID"`
        windowRole=`getWindowRole "$windowID"`

        echo "$windowName" | grep "priv" > /dev/null 2>&1 && PRIVATE=true || PRIVATE=false

        if [[ "$windowRole" == "browser" ]]; then
            $PRIVATE && echo "desktop=^2" || echo "desktop=^1"
        else
            echo ""
        fi
        ;;
    "Thunderbird")
        windowName=`getWindowName "$windowID"`
        windowRole=`getWindowRole "$windowID"`
        desktopNumber="^3"
        
        if [[ -n "$windowRole" ]]; then
            if [[ "$windowRole" == "3pane" ]]; then
                # Default window
                echo "desktop=$desktopNumber"
            elif [[ "$windowRole" =~ Msgc* ]]; then
                # Message window
                echo "desktop=$desktopNumber split_dir=down split_ratio=0.4"
            elif [[ "$windowRole" =~ addr* ]]; then
                # Contact window
                echo "desktop=$desktopNumber split_dir=left split_ratio=0.3"
            else
                # Others
                echo "desktop=$desktopNumber floating=true"
            fi
        else
            # Others
            echo "desktop=$desktopNumber floating=true"
        fi
        ;;
    "Steam"|"Mumble")
        windowName=`getWindowName "$windowID"`
        windowRole=`getWindowRole "$windowID"`
        desktopNumber="^6"

        steamBase=("false" "")
        steamFriends=("false" "")
        steamChat=("false" "")
        mumbleBase=("false" "")

        # Determine which windows are already present
        for otherID in `bspc query -W --desktop "$desktopNumber" | grep -v "$windowID"`; do
            otherName=`getWindowName "$otherID"`
            case "$otherName" in
                "Steam")
                    steamBase=("true" "$otherID")
                    ;;
                "Friends"|"Amis")
                    steamFriends=("true" "$otherID")
                    ;;
                *"Chat")
                    steamChat=("true" "$otherID")
                    ;;
                "Mumble"*)
                    mumbleBase=("true" "$otherID")
                    ;;
                *)
                    ;;
            esac
        done

        # Place window
        if [[ "$windowClass" == "Steam" ]]; then
        # Steam
            case "$windowName" in
                "Steam")
                    if [[ "${steamFriends[0]}" == "true" ]]; then
                        echo "desktop=$desktopNumber split_dir=right split_ratio=0.8 window=${steamFriends[1]} follow=false focus=false"
                    elif [[ "${mumbleBase[0]}" == "true" ]]; then
                        echo "desktop=$desktopNumber split_dir=left split_ratio=0.3 window=${mumbleBase[1]} follow=false focus=false"
                    else
                        echo "desktop=$desktopNumber follow=false focus=false"
                    fi
                    ;;
                "Friends"|"Amis")
                    if [[ "${steamBase[0]}" == "true" ]]; then
                        echo "desktop=$desktopNumber split_dir=left split_ratio=0.2 window=${steamBase[1]} follow=false focus=false"
                    else
                        echo "desktop=$desktopNumber follow=false focus=false"
                    fi
                    ;;
                *"Chat")
                    if [[ "${mumbleBase[0]}" == "true" ]]; then
                        echo "desktop=$desktopNumber split_dir=up split_ratio=0.5 window=${mumbleBase[1]} follow=false focus=false"
                    elif [[ "${steamBase[0]}" == "true" ]]; then
                        echo "desktop=$desktopNumber split_dir=right split_ratio=0.7 window=${steamBase[1]} follow=false focus=false"
                    else
                        echo "desktop=$desktopNumber follow=false focus=false"
                    fi
                    ;;
                *)
                    echo "desktop=$desktopNumber floating=true"
                    ;;
            esac
        else
        # Mumble
            if [[ "${steamChat[0]}" == "true" ]]; then
                echo "desktop=$desktopNumber split_dir=down split_ratio=0.5 window=${steamChat[1]}"
            elif [[ "${steamBase[0]}" == "true" ]]; then
                echo "desktop=$desktopNumber split_dir=right split_ratio=0.7 window=${steamBase[1]}"
            else
                echo "desktop=$desktopNumber"
            fi
        fi
        ;;
    "Skype")
        windowName=`getWindowName "$windowID"`
        windowRole=`getWindowRole "$windowID"`
        desktopNumber="^8"

        if [[ -n "$windowRole" ]]; then
            if [[ "$windowRole" =~ Conv* ]]; then
                # Conversation window
                echo "desktop=$desktopNumber split_dir=right split_ratio=0.2"
            elif [[ "$windowRole" =~ Call* ]]; then
                # Call window
                echo "desktop=$desktopNumber split_dir=up split_ratio=0.4"
            fi
        else
            if [[ "$windowName" =~ Opt* ]]; then
                # Option window
                echo "desktop=$desktopNumber floating=true"
            elif [[ "$windowName" =~ Trans* ]]; then
                # File transfert window
                echo "desktop=$desktopNumber split_dir=down split_ratio=0.7"
            else
                # Default (contact) window
                echo "desktop=$desktopNumber follow=false"
            fi
        fi
        ;;
    *)
        echo ""
        ;;
esac
