#!/bin/bash
# panel_bar - By BrainlessFrog

# Sourcing functions:
. panel_functions

while read -r line; do
    case $line in
        BAT*)
            daBattery="${line#???}  "
            ;;
        CLOCK*)
            daClock="${line#?????}"
            ;;
        MOC*)
            daMoc="${line#???}"
            ;;
        NET*)
            daNet="${line#???}"
            ;;
        TRAY*)
            daTray="${line#????}"
            ;;
        UPDATE*)
            daUpdate="${line#??????}"
            ;;
        USER*)
            daUser="${line#????}"
            ;;
        VOL*)
            daVol="${line#???}"
            ;;
        W*)
            daWorkspace=`getWorkspace "${line#?}" --pacman --place`
            ;;
    esac
    echo -e "%{l}  ${daUser}  ${daMoc}%{c}  ${daWorkspace}  %{r}${daNetwork}  ${daUpdate}  ${daBattery}${daVolume}  ${daClock} ${daTray}"
done
